install:
  - sudo apt-get update
  - sudo apt-get install qtbase5-dev

script:
  - git submodule init && git submodule update
  - cd qhttp
  - ./update-dependencies.sh
  - cd ..
  - cd qmake LegendsReplay.pro
