install:
  - sudo apt-get update
  - sudo apt-get install qt5-default qt5-qmake

script:
  - git submodule init && git submodule update
  - cd qhttp
  - ./update-dependencies.sh
  - cd ..
  - cd qmake LegendsReplay.pro
