language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9.1

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - qt5-default qttools5-dev-tools
    - g++-6 gcc-6

before_script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5 ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force qt5 ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt562-trusty --yes ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --yes qt56base ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /opt/qt56/bin/qt56-env.sh ; fi
- git submodule init && git submodule update
- qmake -v
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir ./legendsreplay/usr ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir ./legendsreplay/usr/bin ; fi

script:
- cd qhttp
- "./update-dependencies.sh"
- cd ..
- qmake LegendsReplay.pro
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make CXX=g++-6 ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cp ./src/LegendsReplay ./legendsreplay/usr/bin ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then dpkg-deb --build legendsreplay ; fi

before_deploy:
- echo $TRAVIS_TAG
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mv ./legendsreplay.deb ./legendsreplay-$TRAVIS_TAG.deb ; fi

deploy:
  provider: releases
  api_key:
    secure: wJKI+jx7VmdaoAgqoHbg30JvGUi6wePq7jlD8hqWSQcrPUaIeoSaSdx6/r6Rzpna6LQVJqlUJiwpa68MWZI+zTb+cFJgECEqa5X9RErTPLBRO6SNPVBqSntjlyo3iyLJMBguhButmvG0B8gBYXtJrN4N38/0EQVtCh8uVCYx3SFzFvNLc3s1dmOYwkwH+UTuwwDlaAmc1N98Bot6UToglaou3D/t7/8GuOUm4RVijO6zNcMseu5u7RSqe20WB8Orufhs625UKnMPgPXyFeaQ9TD9rMNEgdAe/bA7tLODRvY3kWcGXwwtXCtJzl5iJMChDScrpeXg1OFMjD6dwd+5V8qFtClYMr+KSDBd8OhUs2n6vlyaL+56ROTndF0C41tPIx8lsoY+iUVU2Uqy/r0OZu+3ymbZVaxBXsZhFJPvoHcfSCzZY6Au+0sAkhsRtpVjgM/LroBzppeIPi3ExYEmWs2a9zMD4/GbZGVQd11+BjIhV1/e4DT2YE/04ewUArz6bStjY6RwDzm7yY2yQSihycEDtDuAmmibkXS4msGhJOYrmrgnlAYwgZI3eJnkyyODZZWHXEUFCafnFxjArONax4zqMVCF2EduZKRiTObjnbJJ8qLmrlzlFQODLBUW+GcXVRPXsCDryq1xLtbC8aRQ+f/GumdXSHJq210bsTachCM=
  file: ./legendsreplay-$TRAVIS_TAG.deb
  skip_cleanup: true
  on:
    repo: Aztorius/legendsreplay
    tags: true
    condition: $TRAVIS_OS_NAME = linux
