language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - qt5-default qttools5-dev-tools
            - g++-6
      env: COMPILER=g++-6
    - os: osx
      dist: xcode7.2
      env: COMPILER=clang CXX="g++-6" CC="gcc-6"

before_script:
 - git submodule init && git submodule update
 - qmake -v

script:
 - cd qhttp
 - ./update-dependencies.sh
 - cd ..
 - qmake LegendsReplay.pro
 - make
