dist: trusty

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install --yes qt5-default qttools5-dev-tools

script:
  - git submodule init && git submodule update
  - cd qhttp
  - ./update-dependencies.sh
  - cd ..
  - qmake LegendsReplay.pro
  - make
