language: cpp
dist: trusty

compiler:
 - gcc

os:
 - linux
 - osx

before_script:
 - sudo apt-get update -qq
 - sudo apt-get install --yes qt5-default qttools5-dev-tools
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq
 - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-5; fi
 - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

script:
 - git submodule init && git submodule update
 - cd qhttp
 - ./update-dependencies.sh
 - cd ..
 - qmake LegendsReplay.pro
 - make
