language: cpp
dist: trusty
env: GCC_VERSION=5 CPP=14

compiler:
 - gcc

before_script:
 - sudo apt-get update -qq
 - sudo apt-get install --yes qt5-default qttools5-dev-tools

script:
 - git submodule init && git submodule update
 - cd qhttp
 - ./update-dependencies.sh
 - cd ..
 - qmake LegendsReplay.pro
 - make
