language: cpp
dist: trusty

compiler:
 - gcc

before_script:
 - sudo apt-get update -qq
 - sudo apt-get install --yes qt5-default qttools5-dev-tools
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - sudo apt-get upgrade --yes

script:
 - git submodule init && git submodule update
 - cd qhttp
 - ./update-dependencies.sh
 - cd ..
 - qmake LegendsReplay.pro
 - make
