install:
  - set QTDIR=C:\Qt\5.6\mingw49_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
build_script:
  - git submodule init
  - git submodule update
  - cd qhttp
  - update-dependencies.sh
  - cd ..
  - qmake LegendsReplay.pro
  - mingw32-make