install:
  - choco install -y curl InnoSetup
  - set QTDIR=C:\Qt\5.6\mingw49_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin;"C:\Program Files (x86)\Inno Setup 5"
build_script:
  - git submodule init
  - git submodule update
  - update-dependencies.bat
  - qmake LegendsReplay.pro
  - mingw32-make
  - cp src/release/LegendsReplay.exe .
  - windeployqt --compiler-runtime LegendsReplay.exe
  - cp C:\\Qt\\5.6\\mingw49_32\\bin\\libwinpthread-1.dll .
  - cp C:\\Qt\\5.6\\mingw49_32\\bin\\icudt54.dll .
  - cp C:\\Qt\\5.6\\mingw49_32\\bin\\icuin54.dll .
  - cp C:\\Qt\\5.6\\mingw49_32\\bin\\icuuc54.dll .
  - cp qhttp\\src\\qhttp.dll .
  - iscc setup.iss

artifacts:
  - path: setup-LegendsReplay-*.exe
    name: LegendsReplaySetup
