install:
  - choco install -y curl InnoSetup
  - set QTDIR=C:\Qt\5.6\mingw49_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin;"C:\Program Files (x86)\Inno Setup 5"
build_script:
  - git submodule init
  - git submodule update
  - update-dependencies.bat
  - qmake LegendsReplay.pro
  - mingw32-make
